export const BACKEND_ORIGIN = 'https://admin-test-lt5d.onrender.com';
export const GET_DRIVER_PATH = '/mobileApp/auth';
export const GET_LOADS_PATH = 'mobileApp/getLoad';
export const UPDATE_TRUCK_PATH = '/mobileApp/updateTruck';
export const SET_LOCATION_PATH = '/mobileApp/setTruckLocation';
export const LOCATION_TRACKING = 'location-tracking';
export const BACKGROUND_FETCH_TASK = 'background-fetch';
export const BACKGROUND_GEOFENCE_TASK = 'background-geofence';
export const LOCATION_UPDATE_INTERVAL = 1000 * 60 * 3;
